<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>CinnamonCoffee</AssemblyName>
    <RootNamespace>CinnamonCoffee</RootNamespace>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ScriptHookVDotNet3" Version="3.6.0" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

</Project>
